apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Go-Bumblebee-Jazz
    category: Application
    version: 0.7.1
    dependentOnVendorService: EKS
spec:
  global:
    env:
      - name: GITHUB_USER
        value: cc4i
      - name: GIT_ACCESS_TOKEN
        value: $(self.inputs.gitAccessToken)
      - name: APP_REPO
        value: $(self.inputs.appRepo)
      - name: APP_BRANCH
        value: $(self.inputs.appBranch)
      - name: APP_CONF_REPO
        value: $(self.inputs.appConfRepo)
      - name: KMS_KEY_ID
        value: $(self.inputs.kmsKeyID)

  preRun:
    stages:
      - name: CreateRepository
        command: |
          curl -H "Authorization: token $GIT_ACCESS_TOKEN" --data '{"name":"'$APP_CONF_REPO'", "private": true}' https://api.github.com/user/repos
        readinessProbe:
          command: |
            retcode=`curl -s -o /dev/null -w "%{http_code}" https://github.com/$GITHUB_USER/$APP_CONF_REPO`
            if [ $retcode -ne 200 ]
            then
              echo 'failed to create repo" >&2
              exit 1
            fi
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 1
      - name: PrepareAppContent
        command: |
          cd $TILE_HOME
          git clone https://github.com/$GITHUB_USER/$APP_REPO.git
          cd $APP_REPO
          git checkout $APP_BRANCH
          git pull
          prod_redis_endpoint=$(self.inputs.prodRedisEndpoint)
          if [ $prod_redis_endpoint = "" ]
          then 
            cd manifest/kustomize/prod/air
            sed -i -e 's/redis-cart:6379/'$prod_redis_endpoint'/g' air-deployment.yaml
          fi
      - name: SyncAppContentToRepository
        command: |
          cd $TILE_HOME
          git clone https://$GIT_ACCESS_TOKEN:x-oauth-basic@github.com/$GITHUB_USER/$APP_CONF_REPO.git
          cd $APP_CONF_REPO
          cp -r ../$APP_REPO/manifest/* .
          git add -A
          git commit -m "first commit"
          # !!!Dice has setup already!!!
          # git config --global user.email "robot@codebuild.aws"
          # git config --global user.name "robot"
          # 
          git push
      - name: CreateSecrets
        command: |
          cd $TILE_HOME/scripts
          ./create-secrets.sh github-bumblebee $GITHUB_USER $GIT_ACCESS_TOKEN $APP_CONF_REPO
      - name: RegisterAir2Codebuild
        command: |
          cd $TILE_HOME/scripts
          ./import-source-credential.sh
          ./create-iam-role.sh
          ./register-to-codebuild.sh
      - name: PrepareKubeConfig
        command: |
          cd $TILE_HOME
          export AWS_REGION=`aws configure get region`
          export KUBECONFIG=$TILE_HOME/kube.config
          aws eks update-kubeconfig --name $(self.inputs.prodClusterName) --region $AWS_REGION --role-arn $(self.inputs.prodMasterRoleARN) --kubeconfig $TILE_HOME/kube.config
          kubectl create ns go-bumblebee
          aws eks update-kubeconfig --name $(self.inputs.stageClusterName) --region $AWS_REGION --role-arn $(self.inputs.stageMasterRoleARN) --kubeconfig $TILE_HOME/kube.config
          kubectl create ns go-bumblebee
      - name: SetupDeploymentWithArgocd
        command: |
          cd $TILE_HOME/manifest/argocd
          ARGOCD_TOKEN=`curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/session -d $'{"username":"$(self.inputs.argocdUser)","password":"$(self.inputs.argocdPassword)"}'|jq -r '.token'`

          # add git repo
          githubRepo=$(echo https://$GIT_ACCESS_TOKEN:x-oauth-basic@github.com/$GITHUB_USER/$APP_CONF_REPO.git | sed -e "s#/#\\\/#g")
          sed -e 's/__github_repo__/'$githubRepo'/g' \
              -e 's/__github_access_token__/'$GIT_ACCESS_TOKEN'/g' ./add-repo.json > ./add-repo-go.json
          curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/repositories -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@add-repo-go.json"

          # add staging deployment 
          sed -e 's/__github_repo__/'$githubRepo'/g' ./stage-all-in-one.json > ./stage-all-in-one-go.json
          curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/applications -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@stage-all-in-one.json"

          # add production cluster
          kubectl apply -f ./argocd-remote.yaml
          prodClusterArn=$(echo $(self.inputs.prodClusterArn) | sed -e "s#/#\\\/#g")
          prodClusterEndpoint=$(echo $(self.inputs.prodClusterEndpoint) | sed -e "s#/#\\\/#g")

          sed -e 's/__caData__/$(self.inputs.prodClusterCertificateAuthorityData)/g' \
              -e 's/__name__/'$prodClusterArn'/g' \
              -e 's/__server__/'$prodClusterEndpoint'/g' ./add-cluster.json > ./add-cluster-go.json
          curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/clusters -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@add-cluster-go.json"
          
          # add production deployment
          sed -e 's/__server__/'$prodClusterEndpoint'/g' \
              -e 's/__github_repo__/'$githubRepo'/g' ./prod-all-in-one.json > ./prod-all-in-one-go.json
          curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/applications -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@prod-all-in-one-go.json"

  inputs:
    - name: gitAccessToken
      inputType: String
      require: true
    - name: appRepo
      inputType: String
      require: true
    - name: appBranch
      inputType: String
      require: true
    - name: appConfRepo
      inputType: String
      require: true
    - name: kmsKeyID
      inputType: String
      require: true
    - name: argocdBaseUrl
      inputType: String
      require: true
    - name: argocdUser
      inputType: String
      require: true
    - name: argocdPassword
      inputType: String
      require: true
    - name: prodClusterCertificateAuthorityData
      inputType: Base64
      require: true
    - name: prodClusterArn
      inputType: String
      require: true
    - name: prodClusterEndpoint
      inputType: String
      require: true
    - name: prodClusterName
      inputType: String
      require: true
    - name: prodMasterRoleARN
      inputType: String
      require: true
    - name: stageClusterName
      inputType: String
      require: true
    - name: stageMasterRoleARN
      inputType: String
      require: true  
    - name: prodRedisEndpoint
      inputType: String
      require: true  


  # Ouptputs represnt output value after launched, for 'ContainerApplication' might need leverage specific command to retrive output.
  outputs:
    # FromCommand
    - name: appConfRepo
      outputType: String
      defaultValueCommand: echo https://github.com/$GITHUB_USER/$APP_CONF_REPO.git
      description: Custom::GitHub        

  notes: []

